apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bt6z
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/abhindas-tenant/devfile-sample/devfile-sample-bt6z@sha256:afd3ce480b96835892359d137ed77a6ca2ea1066c9fa777bbd0969f3088e95f4
        name: my-nodejs
        resources: {}
status: {}
